language: r
sudo: false
cache: packages
warnings_are_errors: true  # true is default

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_CRAN_INCOMING_=true
    - _R_CHECK_FORCE_SUGGESTS_=false
    - MAKEFLAGS="-j 2"
    - LC_ALL="en_US.UTF-8"

# These packages are just prefixed with `r-cran-` and pulled with apt from
# c2deb4u.
# The automatic dependency check on linux will always build from source, which
# takes a very long time. Preinstall packages to hopefully avoid that.
# Note that some names here are not equivalent with their CRAN names (cOde ->
# code, ...). During package dependency check it will *still* try to update all
# dependencies to their latest version and rebuild everything that does not
# have a corresponding binary package.
# This list only works for linux builds as MacOS is pulling binary packages
# from CRAN itself.
r_binary_packages:
  - rpf
  - data.table
  - mize
  - loo
  - progress
  - reshape
  - checkmate
  - hms
  - inline
  - jsonlite
  - remotes
  - knitr
  - testthat
  - devtools
  - shiny
  - code
  - deoptim
  - ggally
  - gridextra
  - matrixstats
  - openmx
  - rstan
  - rstantools
  - deriv

matrix:
  include:
    - os: linux
      dist: xenial
      r: release
    - os: linux
      dist: bionic
      r: release
      # do we really need/want -O3 and mtune/march native? If so, thi should go into package src Makevars
    #  env: CC="gcc-7" CXX="g++-7" CXX14="g++-7 -fPIC -std=c++1y" CXX14FLAGS="-mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3"
    - os: linux
      dist: bionic
      r: devel
    - os: osx
      osx_image: xcode10
      r: release
      fortran: false
    #  env: CC="clang" CXX14="clang++ -arch x86_64 -ftemplate-depth-256" CXX14FLAGS="-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-unknown-pragmas"
      # Override this array to an empty value, because automatic dependency
      # checks on MacOS will result in binary package download from CRAN
      # anyway. Also, the names from c2deb4u are not consistent with the
      # package names on CRAN (cOde vs code, DEoptim vs deoptim and so on..)
      r_binary_packages: []

before_install:
  # This should be done in the base travis image, really
  - "[[ \"$TRAVIS_OS_NAME\" = 'linux' ]] && sudo locale-gen en_US.UTF-8 || true"

script:
- |
  R CMD build --no-build-vignettes .
  if [[ "$TRAVIS_PULL_REQUEST" != "false" ]] || [[ "$TRAVIS_BRANCH" = "master" ]] ; then
    # Do the full stack of tests and checks on everything that goes into master
    travis_wait 60 R CMD check --no-vignettes --as-cran *tar.gz
  else
    # Do basic testing else
    Rscript -e "install.packages(list.files(pattern='ctsem.*tar.gz'))"
    travis_wait 60 Rscript -e "library(devtools); devtools::test()"
  fi
  # Useful logs when things go wrong with Travis:
  #cat ctsem.Rcheck/00install.out*
  #cat ctsem.Rcheck/ctsem-Ex.Rout*
  #cat ctsem.Rcheck/tests/testthat.Rout*
