language: r
sudo: false
#cache: packages

# TODO
# + build args, though os-matrix specific are considered non-portable
# + default ASCII locale with UTF-8 content in package
warnings_are_errors: false

#repos:
#  CRAN: https://cloud.r-project.org
#  ropensci: http://packages.ropensci.org

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_CRAN_INCOMING_=true
    - _R_CHECK_FORCE_SUGGESTS_=false
    - MAKEFLAGS="-j 2"

r_binary_packages:
  - rpf
  #- rstantools
  #- data.table
  - jsonlite
  #- Rcpp
  #- cOde
  - remotes
  #- Deriv
  #- mvtnorm
  - knitr
  - testthat
  - devtools
  - shiny
  #- mize
  #- StanHeaders
  #- OpenMx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gfortran-7
      - r-cran-rstan

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      env: CC="gcc-7" CXX="g++-7" CXX14="g++-7 -fPIC -std=c++1y" CXX14FLAGS="-mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" LC_ALL="en_US.UTF-8"
    #- os: linux
    #  dist: trusty
    #  r: devel
    #  env: CC="gcc-7" CXX="g++-7" CXX14="g++-7 -fPIC -std=c++1y" CXX14FLAGS="-mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3"
    - os: osx
      osx_image: xcode10
      r: release
      fortran: false
      env: CC="clang" CXX14="clang++ -arch x86_64 -ftemplate-depth-256" CXX14FLAGS="-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-unknown-pragmas" LC_ALL="en_US.UTF-8"

before_install:
  - mkdir ~/.R && env >> ~/.R/Makevars # slight overkill
  - cat ~/.R/Makevars
  - sudo locale-gen en_US.UTF-8

script:
  - travis_wait 30 R CMD build --no-build-vignettes .
  - travis_wait 30 R CMD check --no-vignettes --as-cran  *tar.gz
